---

- name: Set ansible_connection fact to 'network_cli'
  set_fact:
    cloud_vpn_responder_ansible_connection: network_cli

- name: Set responder user fact to 'admin' if not defined
  set_fact:
    cloud_vpn_responder_user: "{{ cloud_vpn_responder_user | default('admin') }}"

- name: Set responder outside interface fact to 'GigabitEthernet1' if not defined
  set_fact:
    cloud_vpn_responder_outside_interface: "{{ cloud_vpn_responder_outside_interface | default('Management') }}"
